# Generated by Django 3.0.7 on 2020-06-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_topic_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='course',
        ),
        migrations.AddField(
            model_name='order',
            name='course',
            field=models.ManyToManyField(to='myapp.Course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='levels',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
