# Generated by Django 3.0.7 on 2020-07-04 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Total_Cost',
        ),
    ]
