# Generated by Django 3.0.7 on 2020-07-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200719_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Order Confirmed')], default='1'),
        ),
    ]
