# Generated by Django 3.0.7 on 2020-07-28 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200721_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
